"""add users table

Revision ID: 527bac95090c
Revises: 03d9bb0aaa7e
Create Date: 2026-03-28 17:30:17.846506
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '527bac95090c'
down_revision: Union[str, None] = '03d9bb0aaa7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('price_data_time_idx', table_name='price_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('price_data_time_idx', 'price_data', [sa.text('time DESC')], unique=False)
    # ### end Alembic commands ###
