"""add users gable

Revision ID: 6d721d537e5f
Revises: 3405cdecef2f
Create Date: 2026-03-28 18:45:52.675655
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '6d721d537e5f'
down_revision: Union[str, None] = '3405cdecef2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
